### ISSUE TITLE
Generate with CSS throws errors with normalize.css

### ISSUE THREAD

**Issue by isGabe** [pattern-lab/patternlab-php#105]
This one is weird...It took me awhile to narrow it down, but it seems that the Generate with CSS command does not like normalize.css. I'm including the [normalize 3 CSS code](https://raw2.github.com/necolas/normalize.css/master/normalize.css) as a .scss file, and generating CSS with compass. I get a screen full of the following when normalize is included:

```
PHP Warning:  DOMXPath::evaluate(): Undefined namespace prefix in [local-path]/core/lib/CSSRuleSaver/SelectorDOM.php on line 95
PHP Warning:  DOMXPath::evaluate(): Invalid expression in [local-path]/core/lib/CSSRuleSaver/SelectorDOM.php on line 95
PHP Notice:  Trying to get property of non-object in [local-path]/core/lib/CSSRuleSaver/SelectorDOM.php on line 119
```

I tried to find possible weird characters, deleting portions of the normalize code until it was all gone, etc, but the only thing that seems to work is not including it all. 

FWIW I was originally using normalize 2.1.3 with the same result.

Any ideas?

**Comment by Shwetha9** [comment]
Any updates on this? Getting the same warning repeatedly: Warning: DOMXPath::evaluate(): Undefined namespace prefix

**Comment by dmolsen** [comment]
@Shwetha9 -

It's a problem with the library I use to do the selector stuff. It's not easily fixed especially as I'm well into PL2. For now I would just skip trying to use the CSS feature.

**Comment by Shwetha9** [comment]
Ok, thanks!

**Comment by sealfur** [comment]
@dmolsen Is there any danger in continuing to use it and just ignoring the errors?
