### ISSUE TITLE
Develop a Better Initial State That Doesn't Require Nuking All The Things

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php#117]
While `core/source/` is a nice starting point for the demo it can be confusing to others on what can and can't be used. It might be better to have an amazingly slim `core/source/` as a starting point and then save current `core/source/` as a custom boilerplate we use to generate the actual demo.

/cc @joshrcook

**Comment by jaicab** [comment]
A Modernizr-like custom boilerplate generator would be much appreciated. I would love to help with that. I'm trying to integrate Pattern Lab as part of the front-end workflow at my company and although we have a basic boilerplate we feel like there is a need for this. 

Checkboxes could determine whether to use Sass / LESS / Vanilla CSS, Grunt and which patterns to include, for example.

**Comment by dmolsen** [comment]
@jaicab -

I think the current game plan is to rely on a Yeoman generator for that. Some folks put together [Yeo+Lab](http://yeo-lab.com) which I think is an interesting solution to this problem. I've already put together a [thin edition of PL2](https://github.com/pattern-lab/edition-php-thin) to better serve the Yeo+Lab project. Alternatively, groups could create their own editions of PL2 that included their own StarterKits ([example](https://github.com/pattern-lab/starterkit-mustache-demo)) so they could start projects on the same page. PL2 is a work in progress as I'm still solidifying the plug-in architecture. It works though.

**Comment by coxrichuk** [comment]
Just to put my cents in ....

We have used PL as a base framework for our complete front-end workflow and found ourselves just stripping out the majority of what was included by default and ended up just including one "demo" pattern per type for anyone new coming to the framework.

This also allows us to reuse commonly used patterns (how many of us continuously reuse the same menu html structure time and time again !).

The boilerplate is then controlled using a mixture of Yeoman, Grunt and Bower.
