### ISSUE TITLE
TWIG port?

### ISSUE THREAD

**Issue by ryanbelisle** [pattern-lab/patternlab-php#149]
Hey guys,
Not really an issue, I wasn't sure where to post the concept. But I was curious to see if anyone had any insight to how easy or hard it would be to port PatternLab to use TWIG instead of Mustache for the template language?

I'm a noob to TWIG and PHP programming in general so I'm not sure if this would even be possible for me.

The reason for the inquiry is I'm trying to create a better workflow between front-end prototyping and actual implementation by lets say, a PHP developer/engineer. We use TWIG for templates with our software, so it would make sense to use TWIG to template the static prototypes, since it's in the same language.

Thoughts? Unless I'm overthinking this?

**Comment by PayBas** [comment]
Any update on this?

**Comment by dmolsen** [comment]
@PayBas -

PL2 is still in limbo. It's suffered from serious scope creep and a time squeeze. Finding big chunks of time I can dedicate to it has been tough. I'm on the downward slope but I'd hate to give a delivery date as I've blown through the last several that I've given.

**Comment by mospeed** [comment]
Hello Everyone,

Although this is an old thread but was there any work done on this. Or is there any other solution to this requirement. I am looking at this from drupal 8 development perspective. Any pointers will be helpful.

Thanks

**Comment by derhasi** [comment]
The twig edition is around for a while now: see http://patternlab.io/download.html for an overview. There is a [Drupal Edition](https://github.com/pattern-lab/edition-php-drupal-standard) now too, and for example [Pattern-Lab-Starter by Phase2](https://github.com/phase2/pattern-lab-starter).

**Comment by mospeed** [comment]
Picking up the thread from the below point mentioned earlier in the conversation. Question is that can the PL template can still be mustache but he built output for drupal can be twig. Is it too farfetched ?

"What I'm hoping we can do towards summer is develop a "converter" step that can convert from the very simple Mustache syntax into other languages like Twig or"

My Frontend guys rotate on a regular basis and asking them to build in Twig will be difficult and will face lot of resistance.
