### ISSUE TITLE
Generating for the first time on Ubuntu (Koding)

### ISSUE THREAD

**Issue by krulik** [pattern-lab/patternlab-php#155]
Hey,
I've ran into a problem with a fresh install of PL on a fresh Koding VM.
I'm on Ubuntu with PHP 5.4.9.

I've git-cloned PL and ran `php core/builder.php -g` from the root dir.
I however get the following error:
`
configuring pattern lab...
upgrading your version of pattern lab...
checking for migrations...
   Starting the 003-move-styleguide migration...
   Completed the 003-move-styleguide migration...
PHP Fatal error:  Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(/home/sergek/Web/pl-test/core/lib/PatternLab/../../../source/_patterns/00-atoms/00-meta/): 
failed to open dir: No such file or directory' in /home/sergek/Web/pl-test/core/lib/PatternLab/Migrator.php:47
Stack trace:
#0 /home/sergek/Web/pl-test/core/lib/PatternLab/Migrator.php(47): DirectoryIterator->__construct('/home/sergek/We...')
#1 /home/sergek/Web/pl-test/core/lib/PatternLab/Configurer.php(69): PatternLab\Migrator->migrate(true)
#2 /home/sergek/Web/pl-test/core/builder.php(75): PatternLab\Configurer->getConfig()
#3 {main}

  thrown in /home/sergek/Web/pl-test/core/lib/PatternLab/Migrator.php on line 47
`

I've tried looking into related issues ( #121 , #111 ) but they're talking about JSON problems, which I don't seem to have (in any case I've ran `php -i | grep -i json` and got that I have version 1.2.1 installed).

I'm sorry to bother but I'll be really grateful if you can help me quickly, in a few hours I have a class to instruct and it doesn't work (of-course the blame of last-minute testing is on me :))

Thanks!

**Comment by fmitchell** [comment]
Was seeing the same error on OX 10.10.2.

```
└╼ php core/builder.php -v
configuring pattern lab...
You're running v0.7.12 of the PHP version of Pattern Lab.
```

```
PHP 5.5.14 (cli) (built: Sep  9 2014 19:09:25)
Copyright (c) 1997-2014 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2014 Zend Technologies
```

```
└╼ php core/builder.php -g
configuring pattern lab...
upgrading your version of pattern lab...
checking for migrations...

Fatal error: Uncaught exception 'UnexpectedValueException' with message 'DirectoryIterator::__construct(../patternlab/core/lib/PatternLab/../../../source/): failed to open dir: No such file or directory' in ../patternlab/core/lib/PatternLab/Migrator.php:53
Stack trace:
#0 ../patternlab/core/lib/PatternLab/Migrator.php(53): DirectoryIterator->__construct('/Users/fredric/...')
#1 ../patternlab/core/lib/PatternLab/Configurer.php(69): PatternLab\Migrator->migrate(true)
#2 ../patternlab/core/builder.php(75): PatternLab\Configurer->getConfig()
#3 {main}
  thrown in ../patternlab/core/lib/PatternLab/Migrator.php on line 53
```

I had to build the folders using the steps you highlighted above.
