### ISSUE TITLE
How to compile scss files

### ISSUE THREAD

**Issue by magique** [pattern-lab/patternlab-php#16]
Loving the pattern lab you've created!

How are the scss files meant to be compiling?
I'm used to using a config.rb file in the root of my projects.

I'm running pattern lab locally on my macbook, using the following command to watch the project for changes:
<code>php builder/builder.php -w</code>

Please let me know if I'm missing something - I've read through the docs and couldn't see anything about compiling.

**Comment by robrecord** [comment]
Yes, mightily confused about why my sass/scss didn't get compiled. Using node it shouldn't be hard to add a gulp/grunt task for this by default.
