### ISSUE TITLE
Link variable 

### ISSUE THREAD

**Issue by bradfrost** [pattern-lab/patternlab-php#161]
I'm really diving into using the `link` variable (http://patternlab.io/docs/data-link-variable.html), and am absolutely loving it.

One thing I'd like to be able to do is link to other patterns with `_data.json`. I set a lot of my patterns up like so:

`<a href="{{ url }}">` 

and would love to be able to point that `{{ url }}` to other patterns. Is this possible?

**Comment by makeaweli** [comment]
Is this part of the current master?

**Comment by bradfrost** [comment]
@makeaweli It sure is. You can learn more about it [here](http://patternlab.io/docs/data-link-variable.html)
