### ISSUE TITLE
Print functionality

### ISSUE THREAD

**Issue by jeremiecarlson** [pattern-lab/patternlab-php#218]
I have some developers that I work with that are requesting a way to be able to print out a template with the annotations, similar to other wireframes that they are used to. 

I believe the ideal scenario would be to have the layout at a given size printed with the annotations (including numbering) on the same sheet of paper, but I'd appreciate any sort of direction that got me close to that.

**Comment by corinafong** [comment]
This would be great! I'm including patternlab into our workflow and this would be a great feature. Just wondering if this is still in the works?

**Comment by bradfrost** [comment]
The ability to print is easy enough to implement in the list views. I'm currently redesigning the 'view all' page for the new version of PL, so I'll make sure to prioritize the printed version of that screen.

The numbered in-context annotations is a fantastic idea, and will require some thought and consideration. I think it's possible, but will require some elbow grease to execute.
