### ISSUE TITLE
Cannot use Pattern Parameters

### ISSUE THREAD

**Issue by thangkieu** [pattern-lab/patternlab-php#224]
Hi all!
I have an issue with pattern parameters.
- first: I've defined an property in data.json: "message": "Some-text"
- create an mustache file: 01-base-button.mustache in atoms folder with content:
  <button class="base-button">
  <span class="base-button-text">{{ message }}</span>
  </button>
- create other mustache file: 01-test-pattern.mustache in molecules folder with content:
  {{> atoms-base-button(message: "Other text") }}
  But when I select test-pattern to show the result, It's not work. Just blank page showed.

What am I wrong? Help me please?
Thanks so much

**Comment by hschot** [comment]
With the 0.9.1 [node version of Patternlab](https://github.com/pattern-lab/patternlab-node), I also still have this issue. @dmolsen have you tried it with Patternlab node? (Not requesting you to go through the trouble of setting it up, just asking if you already have ;-)

**Comment by bmuenzenmeyer** [comment]
@hschot correct it's not implemented in Pattern Lab Node yet, but I'm working on it now :D

**Comment by jackblackCH** [comment]
+1
