### ISSUE TITLE
Request: Front page != View All

### ISSUE THREAD

**Issue by dennisfrank** [pattern-lab/patternlab-php#228]
Pattern Lab’s front page loads every single pattern. This could be **a lot of stuff**.

On a current install this behaviour breaks many (mobile) browsers because we have many patterns with complex and dynamic functionality and lots of layout images.

I would a prefer an empty front page or an config option to choose a front page pattern. For example you could create a template with some project specific infos or links to selected patterns.

**Comment by dmolsen** [comment]
Related to this... the next version of PL allows dropping individual patterns from the view all pages too.

**Comment by numanWD** [comment]
Thanks @jamiemagique for the help.!!!!

@dmolsen Do you know when the next version would be ready?
