### ISSUE TITLE
Can't change the data 

### ISSUE THREAD

**Issue by wpaflightpath** [pattern-lab/patternlab-php#239]
I was trying to change the _data.json file but my loads (which work when changing the pattersn) don't seem to update any of the data.  It doesn't even seem to recognize that I have edited the json file.  

I am using:
`php core/builder.php -wr`

and the results I get are as follow:
`configuring pattern lab...
your site has been generated...
site generation took 1.1719999313354 seconds and used 3.25MB of memory...
starting page auto-reload...
watching your site for changes...
Could not open input file: C:\inetpub\wwwroot\local`

after editing it shows everything fine:
`03-templates\00-homepage.mustache changed...`

but still no data change

**Comment by wpaflightpath** [comment]
I was able to figure it out, folder structure issue. Sorry I didnt realize this was still opened.

**Comment by conortm** [comment]
:+1:
