### ISSUE TITLE
Using styleGuideExcludes in config.ini produces an "Invalid argument supplied" warning

### ISSUE THREAD

**Issue by jamiemagique** [pattern-lab/patternlab-php#246]
This issue is somewhat related to #242 and #228 

1. Mustache files created inside sub folders of the first level of the _patterns folder directory get a 'View all' page and get added into the 'All' page
2. Adding sub folders to templates and pages for organisation makes those patterns appear in the 'All' page
3. You can use `styleGuideExcludes` inside `config.ini` to exclude these folders from appearing in the 'All' page, which also removes the 'View all' pages for each of those sub folders

`styleGuideExcludes = "03-templates,04-pages"`

4. If you don't have a mustache file inside the root of a folder when choosing to exclude it using `styleGuideExcludes` inside `config.ini` the `builder.php` returns the following error (from v0.7.12 dev branch)

`“Warning: Invalid argument supplied for foreach() in [PATH]/core/lib/PatternLab/Builder.php on line 958”`

CC: @daigofuji @paulgendek

**Comment by dmolsen** [comment]
Think this is now addressed in this edition of PL as well as the next. Thanks.
