### ISSUE TITLE
PHP Fatal Error when generating a new site

### ISSUE THREAD

**Issue by stephesk8s** [pattern-lab/patternlab-php#250]
I'm on our new intranet server - CentOS 6.5, PHP 5.3.3.

I'm trying to generate the Pattern Lab website and get the following PHP Fatal error:

configuring pattern lab...
upgrading your version of pattern lab...
checking for migrations...
   Starting the 001-move-source migration...
   Completed the 001-move-source migration...
   Starting the 003-move-styleguide migration...
   Completed the 003-move-styleguide migration...
PHP Fatal error:  Call to undefined method SplFileInfo::getExtension() in /websites/intranet/patternlab-php-master/core/lib/PatternLab/Builder.php on line 609

**Comment by zdislaw** [comment]
Requirements page still says 5.3+

**Comment by piers-shepherd-sift** [comment]
Requirements page still says 5.3+

"To use the basic features of Pattern Lab, you must have PHP 5.3+ installed."
