### ISSUE TITLE
Adding paths to the builder recipe

### ISSUE THREAD

**Issue by tedstrauss** [pattern-lab/patternlab-php#251]
Hi, I recently discovered PL and am interested in using it as a front-end builder for a complex Yii app. The idea is to rebuild the Yii views one by one, making for a nice smooth transition.
My question is this: in Builder.php all compiled code goes to public/ but I would like to be able to specify path destinations for each of the **pages** I build, so that they can be targetted to the appopriate section of the Yii code tree. 
Is there a way to add destination path to the source patterns?
I hope my question makes sense. Cheers

**Comment by dmolsen** [comment]
Conceivably this could be implemented with a plug-in with the next version of Pattern Lab. Not going to pursue this in core.
