### ISSUE TITLE
(MQ+ Menu) Media query gathering is gathering all max widths

### ISSUE THREAD

**Issue by wpaflightpath** [pattern-lab/patternlab-php#253]
Is there any way to either , possibly in a future release , have the option to define the MQ+ menu to either have specific breakpoints that are set in the data file or to make sure that the gatherMQs function only finds max or min width that exist after a media query call?

I changed the regular expression to this on my local copy of Builder.php, and it does the trick so far, it just makes sure to find an @ sign before the rest of the media query call... I think... I'm not great with regular expressions

```
preg_match_all("/@.*(min|max)-width:([ ]+)?(([0-9]{1,5})(\.[0-9]{1,20}|)(px|em))/",$data,$matches);
```

I also wound up commenting out the sort just after this because it was doing an alphabetical and not  number sort.

**Comment by dmolsen** [comment]
@wpaflightpath -

Thanks for catching this. Can't believe I overlooked that. This will be in a future release. See [this commit](https://github.com/pattern-lab/patternlab-php-core/commit/a8ec4f053d6d15a2d8eda8bad765b8ba34c93302).
