### ISSUE TITLE
Set default numbering to multiples of 10 so that they can be more easily re-sorted

### ISSUE THREAD

**Issue by mimshwright** [pattern-lab/patternlab-php#258]
For example, change...
00-text
01-layout
02-blocks
03-media
04-forms
...

To 
10-text (start with 10, leaving the possibility to add 00 later)
20-layout
30-media
40-forms
...

**Comment by bradfrost** [comment]
Hey @mimshwright,
Thanks for the suggestion. I don't think we're going to implement that as a global change, and if we were to make a change it would be to remove the numbering altogether. I personally use the numbering system to organize things, but a lot of folks I talk to remove it. At the end of the day it comes down to personal preference!

Thanks again,
B
