### ISSUE TITLE
Right border missing on search molecule

### ISSUE THREAD

**Issue by himedlooff** [pattern-lab/patternlab-php#261]
![image](https://cloud.githubusercontent.com/assets/1093373/5624402/4f412fd8-9532-11e4-8541-9f0611ea47e1.png)

http://demo.patternlab.io/?p=molecules-search

This happens in chrome 39 and safari 7.

**Comment by bradfrost** [comment]
Hi @himedlooff,
Thanks again for pointing this out, and again it won't be fixed as the default code should be discarded.
