### ISSUE TITLE
Alignment of button is off in the newsletter molecule

### ISSUE THREAD

**Issue by himedlooff** [pattern-lab/patternlab-php#262]
http://demo.patternlab.io/?p=molecules-newsletter

chrome 39

![image](https://cloud.githubusercontent.com/assets/1093373/5624416/967103f6-9532-11e4-8d95-e6265e29941d.png)

safari 7

![image](https://cloud.githubusercontent.com/assets/1093373/5624426/d3a58cba-9532-11e4-8938-2ea6fe594f08.png)

**Comment by bradfrost** [comment]
Hey @himedlooff,
Thanks for pointing out the cross-browser issue. It won't be fixed as the demo Pattern Lab setup is meant to be discarded and replaced with your own unique system.

**Comment by himedlooff** [comment]
Would you accept a PR for this if I fixed it? I think my OCD compels me. :smile:

**Comment by bradfrost** [comment]
Ha! I honestly don't think it's worth the time to do. @dmolsen is in the process of getting the new version of Pattern Lab ready, and when that happens all of this is going to go away. So free to change it on your end, but I don't want to open pandora's box by having to manage minor changes to throwaway code.

**Comment by himedlooff** [comment]
Glad I asked, makes sense, thanks!
