### ISSUE TITLE
Accessing a variable in a .mustache file

### ISSUE THREAD

**Issue by israele** [pattern-lab/patternlab-php#263]
Hello! I'm new and don't understand things. I hope you can help. 

I'm trying out a new installation of patternlab and am trying to modify things but I'm not having much luck. The current sticking point is I'm trying to use mustache syntax and failing. 

I wanted to see if I could change a simple thing such as the list of colors that show up in my local patternlab site. So I went to source\_patterns\00-atoms\01-global\00-colors.mustache and added a new <span> element, but one filled with the color variable from the variables file. I've tried using the shorthand syntax as well as the mustache syntax, none of which seem to work. The pattern, no matter what I've tried, can't seem to be found, as reported on the command line by the watcher script. 

This is what I've ended up with. Could you poke it with a stick and tell me how I've gone wrong? 

I tried some funky shorthand, which I feel probably shouldn't work:

```
<span class="sg-swatch" style="background: {{> atoms-colors }} {{gray-med}} {{> atoms-colors }};"></span>
<span class="sg-label">Testing!</span>
```

But the mustache syntax I really thought should work was this:

```
<span class="sg-swatch" style="background: {{> 00-atoms/01-global/00-colors.gray-med }};"></span>
<span class="sg-label">Testing!</span>
```
I guess there are two things going on here... I'm trying to use mustache syntax in a file that doesn't seem to have any other mustache stuff and I'm trying to mangle said syntax into dredging up a variable housed in another mustache file. Are these possible? If so, what's the best way to do these things... if these things are, indeed, preferred practice. If there's a better way to do what I was trying to do, please let me know that as well. 

Thanks!

**Comment by dmolsen** [comment]
@israele -

Are you defining `gray-med` in your Sass file and expecting it to be populated in Mustache? Pattern Lab doesn't work that way. In this case you'd want to define the data in `sources/_data/data.json` or just follow the example in that pattern and hardcode the color value. More [docs on using JSON to define variables](http://patternlab.io/docs/data-json-mustache.html). In the case of CSS variables it's duplication for you but there's not much of a workaround for that.

Just as an FYI, `{{> atoms-colors }}` is a Mustache partial. The `>` is telling Mustache to include a Mustache template within the one referencing it. So in this case you're [referencing the exact mark-up you're editing](https://github.com/pattern-lab/patternlab-php/blob/52eae82235f7f8f4d31410c189c20dc54ecf9e67/core/source/_patterns/00-atoms/01-global/00-colors.mustache). So it won't work within a `style` attribute.

Hope that helps.

**Comment by israele** [comment]
Ahah!  Thank you! I didn't quite grok how things were interconnected.
This helps.

**Comment by dmolsen** [comment]
Sounds good :)

**Comment by dmolsen** [comment]
Sounds good :)
