### ISSUE TITLE
templates and pages are shown in the index when they're placed in subfolders

### ISSUE THREAD

**Issue by mimshwright** [pattern-lab/patternlab-php#264]
/pages
        /home.mustache <-- hidden on index.html
        /products
            /product.mustache <-- not hidden

**Comment by dmolsen** [comment]
@mimshwright -

So PL doesn't actually know anything about "templates" or "pages". It simply iterates over a directory structure and uses the names of directories and files to build out the nav. So if you want more or less nav just rename or remove directories. You don't *have* to use the atomic design metaphor to use PL.

In this case PL makes an assumption that if you're 2 levels deep you want to include the found file in the "view all" views. To turn that off you need to add the full directory name of the section to `styleGuideExcludes` in `config/config.ini`. So in this case you'd use `pages` (I'm assuming you stripped the ordinal). If it still has the ordinal it's be something like `04-pages`. To add multiple just separate by a comma so `03-templates,04-pages`.

Let me know if this works for you.

**Comment by mimshwright** [comment]
That worked for me. Thanks very much!

Just my 2¢, I would suggest that be the default behavior.

**Comment by dmolsen** [comment]
@mimshwright -

Like I said, PL doesn't know anything about "templates" or "pages." We made an early design decision that Atomic Design is not needed when using PL. I'm not sure I'd want to hard code that exclusion even in the config. We could document it better though.
