### ISSUE TITLE
Browser does not Auto Reload

### ISSUE THREAD

**Issue by glolos** [pattern-lab/patternlab-php#266]
If you create a symlink under the source/ folder of PL and do some changes on the .css or .js files that are inside the original folder that the symlink points to, PL does not detect the change and as a result the browser does not Auto Reload

**Comment by dmolsen** [comment]
I'm sure my code for the watch isn't quite as reliable as it should be. I'm rewriting it for PL2 so I won't be returning to the current code base to address this. Sorry.
