### ISSUE TITLE
Missing toolbar on local copy of pattern lab

### ISSUE THREAD

**Issue by israelcevans** [pattern-lab/patternlab-php#269]
Hello!
I've just set up a new clone of patternlab and the newly generated website seems to lack the toolbar that you can see in the Demo. 
I'm running on windows 8.1, I have PHP5.6.5 installed (had to install to generate), and the generated website is there and looks as it usually does, all but the toolbar. 
Would anyone have any ideas on what I might have missed?

Thanks,
~Israel

**Comment by dmolsen** [comment]
@israelcevans -

Wow, that's weird. You have the pull bar but not the header? And you're definitely opening `public/index.html`? Two things... can you attach a screenshot of the generated DOM for `public/index.html`, please? Also, let me know what browser you're running just so I can check that too. Thanks.

**Comment by dmolsen** [comment]
Haven't heard back on this issue so closing it up.
