### ISSUE TITLE
Theme switcher

### ISSUE THREAD

**Issue by bfolliot** [pattern-lab/patternlab-php#271]
I work on a project with several css "theme".
For now, to view the project in other "theme", i need to change the css link in the code.
It would be great to have a menu to switch.

I think the easiest way is to change the head via a menu.

**Comment by dmolsen** [comment]
@bfolliot -

Sorry but I won't be implementing this feature idea. You could possibly implement this as a plug-in in PL2. Though I think you'd always run into the issue that switching between patterns would lose the "theme" choice.

**Comment by TxHawks** [comment]
@bfolliot , if I understand what you want to do correctly, you could, and I think should, achieve this using [pseudo-patterns](http://patternlab.io/docs/pattern-pseudo-patterns.html). 
Simply make the link to the css a mustache variable - something along the lines of:
`<link rel="stylesheet" href="{{ css-url }}">`
Then, have `css-url` mapped to your default css in your `_data.json`, and to the relevant theme in `homepage~theme1.json` or whatever other pattern you want themed.

**Comment by bfolliot** [comment]
Yes it is a good alternative.
Thank you.
