### ISSUE TITLE
Include templates into meta/_head

### ISSUE THREAD

**Issue by timharbour** [pattern-lab/patternlab-php#280]
hey Dave, is it possible to include other mustache templates in atoms/meta/_head and atoms/meta/_foot?
it doesn't seem to do it for me...

eg: 
{{#metatags}}
 {{>meta-tag-template-here}}
{{/metatags}}

**Comment by dmolsen** [comment]
@timharbour -

No. In PL1 the header and footer aren't parsed by Mustache. I'm 99% sure PL2 supports that but I'll double-check and if it doesn't I'll make sure it's added.
