### ISSUE TITLE
Overriding core templates without editting core files?

### ISSUE THREAD

**Issue by barrymcgee** [pattern-lab/patternlab-php#281]
I've just started to build a Pattern Library and would like to make quite a few structural changes to the index page of the pattern library, listing all patterns.

If it right that the only way to do this is to edit the template files in core?

Isn't PatternLab developed in such a way that I should be able to update that core folder whenever a new release appears by just overwriting it or am I missing something?

**Comment by dmolsen** [comment]
@barrymcgee -

In this case, yeah, you'd have to edit core. Their won't be another release that relies on updating core. PL2 is a complete rewrite and, while it isn't completely backwards compatible, hopefully it gives a cleaner upgrade path so you can do what you want to do here without having to worry about my changes.

**Comment by barrymcgee** [comment]
@dmolsen Cool, thank you for the prompt reply and your hard work with Pattern Lab, it's provided me with a fantastic base.
