### ISSUE TITLE
Pattern Lab compiled output uses &gt &lt instead instead of > <

### ISSUE THREAD

**Issue by ygrei** [pattern-lab/patternlab-php#282]
The .mustache files produced when I run Pattern Lab produces &gt instead of > etc.  Which makes the resulting output harder to read and harder to copy/paste into production code.   Is there a way to control such output options?

**Comment by dmolsen** [comment]
@ygrei -

The `.mustache` files under `public/` are meant to be used in the front-end "code panel." They're just copies of the Mustache files in `source/` so I'm not sure how adding output options would help in any way. You already have access to the code.
