### ISSUE TITLE
Allow patterns partials to accept mustache variables as parameters [enhancement]

### ISSUE THREAD

**Issue by stephaniehobson** [pattern-lab/patternlab-php#285]
I hope I've gotten the terminology right.

Basically, I want to create an atom that is a text input:

```
<input
    type="text"
    id="{{ id }}"
    class="form-input"
    {{# required }}required{{/ required }}
    size="{{ maxLength }}"
    maxlength="{{ maxLength }}"
>
``` 

Then I want to create a molecule out of my text input atom, and my label atom:

```
<div class="form-row">
    {{> atoms-label(text: {{ labelText }}, for: {{ inputId }}, required: {{ required }}  ) }}
    {{> atoms-input-text(id: {{ inputId }}, required: {{ required }} ) }}
</div>
``` 

Then I want to create an organism out of my form-row molecules:

```
<form>
{{> molecules-row( labelText: 'Full Name', inputId: 'name' , required: false }}
{{> molecules-row( labelText: 'Email Address', inputId: 'email', required: true) }}
{{> molecules-button(text: "Sign Up!" ) }}
</form>
```

In an ideal world I'm able to specify defaults and only pass the over-ride if there is one... like how the .json data works :) 

It's possible I am trying to stretching this tool into something it was never meant to be but I feel like I'm repeating a little too much code with the way I have it setup now.

**Comment by stephaniehobson** [comment]
Nevermind, I seem to have what I want working with the .json data stuff now :D

**Comment by stephaniehobson** [comment]
Spoke too soon, can't do it. The .json data stuff isn't inherited the way I thought it was. I would also be okay with a json solution to this problem but what I'm trying to achieve is the same as I outlined above. I shouldn't be prescribing solutions anyway, I should be outlining the problem and letting the experts create a solution. I'm a terrible client. I'm not even paying :P

Anyway, this is what I thought would work but didn't.

I set up `01-label.mustache` for my labels which pulled from `_data.json` for its setup
```
<label for="{{ form.id }}" class="form-label{{# form.error }} is-error{{/ form.error }}">{{ form.label.text }} {{# form.required }} <abbr title="Required">*</abbr>{{/ form.required }} {{# form.error }}<strong class="form-error-message">{{ form.label.error-message }}</strong>{{/ form.error }}</label>
```

Then I created `02-label-other.mustache` atom which included this one
```
{{> atoms-label }}
```

With `02-label-other.json` file to change the label text:
```
{
	"form" : {
		"label" : {
			"text" : "Other:"
		}
	}
}
```

This atom displays with the label "Other:" as I expect it to.

Then I included that atom into `03-group-other.mustache`
```
{{> atoms-label-other }}
```

I did not create a .json file to accompany `03-group-other.mustache` and label text from _data.json displays instead of the label text from `02-label-other.json`.

**Comment by TxHawks** [comment]
@stephaniehobson -

pattern-specific jsons are just that - pattern specific. The data in them is not inherited by other patterns.

If I correctly understand what you are trying to do, there are currently two ways I can think of to do so:

1. Write a `03-group-other.json`. This, in turn won't be inherited when you include this pattern. 
2. Use pattern-parameters when you include the atom: `{{> atoms-label(label.text: "Other:" }}`. this will be inherited, but keep in mind - pattern parameters are not real Mustache, and cannot be overridden by json files.

**Comment by stephaniehobson** [comment]
1. Won't work because the ultimate goal there is to include multiple patters which include `label` and I don't want them saying the same thing.
2. I reverted to pattern-parameters :) But I'm still duplicating a lot of the wrapper code :/

**Comment by dmolsen** [comment]
@stephaniehobson -

I had to make a sort of "damned if you do damned if you don't" choice on data inheritance. Seemed like a rabbit hole as I'd have to parse every included pattern for other patterns to snarf in their data and then something would get overwritten that wasn't supposed to be. 

When you say you're duplicating wrapper code do you mean the `<form>` or `<div>` code from your example above?

**Comment by stephaniehobson** [comment]
Yeah, the `<form>` and `<div>` code is exactly what I mean.
