### ISSUE TITLE
/public/styleguide folder

### ISSUE THREAD

**Issue by barrymcgee** [pattern-lab/patternlab-php#286]
I'm a little confused as to how this should work and hoping someone can clarify. Shouldn't this be generated every time the /core/builder.php script is run?

I assumed this and git ignored this whole folder from version control but now when other devs pull it down the repo and try to generate the Pattern Lab locally, they get an error saying this folder needs to be there and should be copied from core?

**Comment by bradfrost** [comment]
> Shouldn't this be generated every time the /core/builder.php script is run?

The new version of PL will deal with this differently, but yes v1 of Pattern Lab is admittedly a bit confusing and inefficient. The `styleguide` directory doesn't come from `source` and instead is pulled from `core`
