### ISSUE TITLE
Back button broken when viewing individual patterns

### ISSUE THREAD

**Issue by barrymcgee** [pattern-lab/patternlab-php#287]
This bug is in my local install and also in the hosted demo.

It is present in Chrome and Firefox but not Safari.

1. Navigate to http://demo.patternlab.io/
2. Click on the 'Colors' pattern
3. You'll now be on http://demo.patternlab.io/?p=atoms-colors
4. Press the back button in your browser

Expected result: You would result to homepage

Actual result: Nothing happens

**Comment by dmolsen** [comment]
@barrymcgee -

Looks like a bug going back to "all." Back and forward seem to work for me for other patterns. Thanks for the heads up.
