### ISSUE TITLE
How to use mustache lambdas

### ISSUE THREAD

**Issue by uris-olmero** [pattern-lab/patternlab-php#289]
I would like to use lambdas with mustache and as I understand this should be possible (even if not in json files). Any suggestions where/if in custom php code I could use mustache lambdas?
I'm trying to bring the mustache templates in our application after front end development with as little changes as possible and this would solve most problems.

Thanks already for any hints.

**Comment by dmolsen** [comment]
@uris-olmero -

This isn't possible in this edition of Pattern Lab because of how we populate the data hash. PL2 has support for it though I feel I've over engineered it some.

**Comment by uris-olmero** [comment]
Ok, I have looked a bit into patternlab source and I have added possible solution in #300
