### ISSUE TITLE
active class not firing for nav and search

### ISSUE THREAD

**Issue by nickcomito** [pattern-lab/patternlab-php#290]
Out of the "box" the active class isn't being applied to nav or search on small viewports. I'm currently viewing Patternlab locally through the public index file, not through apache. Maybe this is causing errors? Any help would be much appreciated! I'm also getting console errors which could be a separate issue.

![nav](https://cloud.githubusercontent.com/assets/3053374/7192833/1d2defe6-e45f-11e4-8c92-aca4ec77830d.jpg)
![screen shot 2015-04-16 at 5 36 16 pm](https://cloud.githubusercontent.com/assets/3053374/7192832/1d2d73f4-e45f-11e4-924a-71e1fa57c0fa.png)

**Comment by nickcomito** [comment]
Looks like this is happening on the demo site too: http://demo.patternlab.io/

**Comment by bradfrost** [comment]
I'm closing this out simply because the demo site isn't meant to be used in any way, shape, or form. The upcoming new version of PL will [remove all this](https://github.com/pattern-lab/edition-php-development/issues/8) so folks will just start with atoms (color swatches, paragraphs, etc).
