### ISSUE TITLE
change style.css directory

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#292]
I want to change the directoty of the style.css file, how and where do I do this? I have a whole booststrap sass project setup already  and I want patternlab to use the current files for this projects. Thanks!

**Comment by daigofuji** [comment]
After you generate, you can edit

**Comment by bradfrost** [comment]
Hey @Machinas,
You can structure your CSS and place it wherever you'd like within the `_source` directory. Once you have your CSS structure in place, you can point to the appropriate CSS path as described above by @daigofuji.
