### ISSUE TITLE
Display CSS related to component

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#293]
Hi,

I was wondering if there was an automatic way to display the CSS related to a component eg. an atom or an organism? There is the option to display the HTML but not the CSS, is this possible?

Thanks!

**Comment by bradfrost** [comment]
Hi @Machinas,
For the new version of Pattern Lab, @dmolsen was making a plugin to pull CSS information for a pattern into Pattern Lab using [KSS](http://warpspire.com/kss/). It's still in the works but that's how you would do it.

**Comment by evoactivity** [comment]
This already exists, currently you need to have your css in the /source/css/ directory (unless you modify `core/lib/PatternLab/Builder.php:1309` which is what I have done.)

Then you can pass in --enablecss / -c when running generate.
