### ISSUE TITLE
Change default page from "all"

### ISSUE THREAD

**Issue by lostsatellites** [pattern-lab/patternlab-php#295]
I haven't seen a setting for this yet, but wondering if there's a way to change the default landing page. I'm creating some intro/overview pages containing process, resource and design tenet info and would like to have that section as the default. For starters I've added an "Overview" directory that will be before "Atoms."

**Comment by dmolsen** [comment]
@lostsatellites -

No, there isn't a setting but you could hack it in. You should be able to change the default `iframe` `src` in `public/index.html`.

**Comment by lostsatellites** [comment]
Thanks man!
