### ISSUE TITLE
How do you change the values of S, M and L for viewport resizing in the nav?

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#296]
I would like to change the settings of the option S, M and L in the top bar which allows you to see the patterns in different viewport sizes. where can this be configured?

Thanks!

**Comment by bradfrost** [comment]
You can find that in [styleguide.js](https://github.com/pattern-lab/patternlab-php/blob/master/core/styleguide/js/styleguide.js), and there are several areas that call a function called `sizeiframe`. You can adjust the values inside of there.

If you want to switch them on or off, you can [configure them in config.ini](http://patternlab.io/docs/advanced-config-options.html)
