### ISSUE TITLE
"this would work better if there was CSS or HTML data"

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#297]
When generating the CSS, it executes for a while but then gives back this message
"this would work better if there was CSS or HTML data" and the CSS doesn't appear when you click "view code". I guess something is not hooked up correctly, but how can I know what is missing or not linked correctly?

Thanks!!

**Comment by dmolsen** [comment]
@Machinas -

That feature is deprecated as of PL2 so I haven't looked at it in a while. Looks like some of the paths are hardcoded. Do you have your CSS in `source/css`? Honestly, it's not that great of a feature. The library I used is old so it doesn't support many of the more recent features of CSS.

**Comment by Machinas** [comment]
Hi @dmolsen it seemed a good feature when it worked, it's something that would be really useful because I need to display the CSS related to each component. The style.scss is in the source folder however within this file, external scss files are imported. Would this be the problem? It'd be great if you could help sort this out or if there is a way to know what is not linked up correctly. Thanks!

**Comment by Machinas** [comment]
Hi I think it was because I had HTML within the mustache files that had no styles assigned to them. Not 100% sure but it works now anyway. Thanks!

**Comment by kserra3** [comment]
@dmolsen I'm a bit sad to see that this feature isn't really being supported anymore. When I read through the documentation for Pattern Lab and I saw this feature, I was excited as it was something I needed for my project. I totally understand about the library being outdated, but it might be worth updating the documentation to warn prospective designers and developers beforehand to set their expectations (or maybe remove the feature if it's unreliable).

**Comment by justb81** [comment]
you can achieve this behavior with [a Javascript-Function](https://gist.github.com/justb81/f80daec9ba22db280337faa24a5e9ff0)

**Comment by romaricdrigon** [comment]
@justb81 thank you for the snippet, could you please elaborate on how to use it?  
Did you achieved to integrate it nicely in Patternlab UI?
