### ISSUE TITLE
Changing colors and fonts displayed in generated styleguide

### ISSUE THREAD

**Issue by fallenturtle** [pattern-lab/patternlab-php#298]
Simpleton question:
The colors and fonts you see listed in the generated style guide... are those supposed to magically rewrite themselves when I update the values in the CSS file or are they static content that I have to update myself via a mustache file?

**Comment by TxHawks** [comment]
@fallenturtle -
They are static content. 
In the stable version of PL (PL1), colors are defined in `source/_patterns/00-atoms/01-global/00-colors/00-colors.mustache` and fonts in `source/_patterns/00-atoms/01-global/00-colors/01-fonts.mustache`

**Comment by dmolsen** [comment]
@fallenturtle -

Sorry, PL is dumb when it comes to that. Tough to come up with a standard that folks would have to follow to make that all automagical. @TxHawks is spot on with where you need to manually change that.
