### ISSUE TITLE
When annotations is open, you can't scroll to view whole component

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#301]
When you open an organism and click annotations, you can't scroll the whole length of the actual organism so you can't see what number the annotations refer to. Maybe just adding margin bottom for an organism page, but I don't think there is way to detect via CSS if you are an organism page or the all components page for example. Thanks

**Comment by bradfrost** [comment]
Thanks for this. Yeah the annotations experience needs a lot of love. We'll
most likely be iterating over this functionality within the new version of
PL. But yeah, I think margin-bottom might be the easiest bet.

__________________________________
Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by Machinas** [comment]
HI thanks for the quick reply, but is there a way to detect when you are within an organism for example, I don't want to add the margin bottom, when all elements appear together.

**Comment by bradfrost** [comment]
I think what you'd want to do is apply the margin (or padding) bottom to
the overall viewport (#sg-viewport)

__________________________________
Brad Frost
http://bradfrost.com
http://twitter.com/brad_frost

**Comment by Machinas** [comment]
@bradfrost  thanks but then that adds padding bottom to the all page, which makes the page have two scroll bars :S any other solution?
