### ISSUE TITLE
Conditional pseudo patterns

### ISSUE THREAD

**Issue by lostsatellites** [pattern-lab/patternlab-php#304]
Is there a way to have conditional pseudo patterns where I could check for one being true and another being false before displaying content?

Example: I only want two examples of a header, one with unauthenticated nav, and one with authenticated. Right now is seems that the pseudo patterns only add content if set to true, when I'd like to replace content with something different.

**Comment by bradfrost** [comment]
@lostsatellites, This can be one of the clunkier aspects of Mustache. Because it's logicless, there's no real if/else statements. 

I've dealt with similar things by doing something similar to the following:
````````````
{{# user.loggedIn }}
{{> organisms-header-authenticated }}
{{/ user.loggedIn }}

{{# user.loggedOut }}
{{> organisms-header-unauthenticated }}
{{/ user.loggedOut }}

````````````

In the global `data.json` file, I'd set one to false by default:

```````````
"user" : {
  "loggedIn" : false,
  "loggedOut" : true
}
````````

Then in the pseudo-pattern, If I wanted to display the logged in header, I'd include this in the json override:

```````````
"user" : {
  "loggedIn" : true,
  "loggedOut" : false
}
````````

Again, this is sort of clunky, but it works. The next version of Pattern Lab is modularized, which means that people could create a Handlebars pattern engine, which includes if/else statements and other stuff.

**Comment by sergejreznik** [comment]
Got an equal problem.

In the data.json I have the statement
`"scroll" : false`

Inside _meta/_01-foot.mustache I have following snippet
`{{# scroll}}
loading scripts, etc.
{{/scroll}}`

On a Page-Template I've got the Page-JSON File named like its mustache-pattern with
`"scroll": true`. Other Parts of the JSON-File are loaded but not the "if-statement".
What to do? 
I want the script to be loaded only on page with this parameter set to true.

Thanks for advice and help.

**Comment by dmolsen** [comment]
I followed your example and couldn't reproduce your problem. Pattern Lab generated the way you wanted it to with `v2.6.0` of Pattern Lab. You can check your version of Pattern Lab by typing the following in a terminal window at the root of your project:

```
php core/console --version
```

**Comment by sergejreznik** [comment]
Hey, just tried it again and it's now working. Working with patternlab gulp node edition (latest release). Package.json shows `version: 1.2.3`.

**Comment by sergejreznik** [comment]
@dmolsen Maybe you got an idea.
- My `data.json`looks like this:
  <img width="275" alt="bildschirmfoto 2016-07-28 um 10 21 03" src="https://cloud.githubusercontent.com/assets/5619563/17205825/0249a1ba-54ad-11e6-9a4a-261ea45654dd.png">
- My `_meta/_01-foot.mustache` - which is loaded on every page - looks like this:
  <img width="354" alt="bildschirmfoto 2016-07-28 um 10 19 52" src="https://cloud.githubusercontent.com/assets/5619563/17205870/2c98782e-54ad-11e6-8954-f1f026764e35.png">
- Then I've got a Page Pattern called `02-index-scroll.mustache` and a `02-index-scroll.json` that looks like:
  <img width="161" alt="bildschirmfoto 2016-07-28 um 10 20 08" src="https://cloud.githubusercontent.com/assets/5619563/17205907/5e6cefc4-54ad-11e6-9615-be4bc0bdb605.png">

In this demo case the `<span class="test">foo 1</span>` should be visible on one specific Page, where the json key is set to true.

My rendered DOM looks like this:
![bildschirmfoto 2016-07-28 um 10 26 26](https://cloud.githubusercontent.com/assets/5619563/17205993/cba89d18-54ad-11e6-84fe-52455bbf63fe.png)

The `span` inside of the "if-statement" is not rendered on the page.

EDIT: I see, it's working if I create a new foot.mustache inside of the `_patterns`folder and include it to the page . But this way it's not dynamically anymore and the JS is loaded in a incorrect way. Or I have to load the JS-Files twice.

EDIT(2): the same conditional statements works inside the `_meta/_00-head.mustache`.
Tried to include a css-file only on the specific page. Works fine. So whats the problem with the `_meta/_01-foot.mustache`?

**Comment by dmolsen** [comment]
@sergejr -

I don't maintain the node version so I'm not much help. I've triple-checked this and it works in PHP. You can cross-post this issue on http://github.com/pattern-lab/patternlab-node if you like.

**Comment by ba55ie** [comment]
Maybe a bit late, but both the PHP and JS versions of Mustache support _inverted sections_:

https://github.com/janl/mustache.js#inverted-sections
https://github.com/bobthecow/mustache.php/wiki/Mustache-Tags#inverted-sections

```
{{# repo }}
  <b>{{ name }}</b>
{{/ repo }}
{{^ repo }}
  No repos :(
{{/ repo }}
```
