### ISSUE TITLE
How do I change the title of my pattern lab style guide?

### ISSUE THREAD

**Issue by guspowell** [pattern-lab/patternlab-php#305]
The title is currently 'Pattern Lab' and I can't seem to change it. I've tried changing it in '_00-head.mustache' and also in '_data.json' but neither works.

**Comment by bradfrost** [comment]
Hey @guspowell,
I believe that title can be changed in `core/templates/index.mustache`. I don't think that's ideal, but perhaps we can address that in Pattern Lab 2. + @dmolsen.
