### ISSUE TITLE
SVG as <object> only visible via "Open in new window" in Chrome/Opera

### ISSUE THREAD

**Issue by bitbitdecker** [pattern-lab/patternlab-php#307]
We're implementing some brand logos as SVGs and we created a kind of slider for that. As a component we want to show it in our pattern lab.

But Chrome and Opera (both Blink) seems to have a weird policy about that and ignores the SVG in the typical pattern lab view (with top bar, annotations and so on). They're shown when you switch to the non-iFrame view.

Firefox and IE11 don't have this issue.

Is there a way to get them visible?

Empty object in iFrame view
![2015-07-01_16h38_13](https://cloud.githubusercontent.com/assets/7779387/8457154/0ba255ea-2010-11e5-94b6-b6b430eead84.png)

Filled object without iFrame
![2015-07-01_16h39_23](https://cloud.githubusercontent.com/assets/7779387/8457155/0ba55664-2010-11e5-8da3-70eb1d4148d4.png)

**Comment by bradfrost** [comment]
@bitbitdecker hmmmm, I'm afraid I'm not sure I have any advice on this. I'll keep my eyes peeled for any solutions.

**Comment by dennisfrank** [comment]
Yeah, same error here. I just spent an hours troubleshooting my SVGs… :(

I know this is the old Pattern Lab, but it is what we use for an project. Any idea for a quick fix? @dmolsen

**Comment by dmolsen** [comment]
I'm assuming this is an issue with security policies, iframes and svg. So outside the scope of PL directly. My Google Fu seems to be lacking but that's the tack I would take in trying to find a solution. Sorry, folks.

**Comment by dennisfrank** [comment]
I kind of fixed it for me by removing the `sandbox` attribute from Pattern Lab’s `#sg-viewport` iframe ([more details](http://www.html5rocks.com/en/tutorials/security/sandboxed-iframes/)).

/core/templates/index.mustache

_Line 37 before changes:_

```html
<iframe id="sg-viewport" sandbox="allow-same-origin allow-scripts"></iframe>
```

_Line 37 after changes:_

```html
<iframe id="sg-viewport"></iframe>
```

@dmolsen What do you think? Is this acceptable as an _official_ fix for the problem?

Embedding SVGs as object is getting more and more popular these days (see [SVG ON THE WEB
A Practical Guide](https://svgontheweb.com/) or [CSS TRICKA - Using SVG](https://css-tricks.com/using-svg/))

**Comment by bitbitdecker** [comment]
@dennisfrank Yes, cool. That kinda fixed this "problem".
