### ISSUE TITLE
PHP Warning:  DOMXPath::evaluate(): Invalid expression in Z:\AlexL\My Documents\ esprit-rwd\patternlab\core\lib\CSSRuleSaver\SelectorDOM.php on line 95

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#308]
Hi,
When generating the CSS ie:

php core/builder.php -gc

I get the following repeated warning:

```
PHP Warning:  DOMXPath::evaluate(): Invalid expression in Z:\AlexL\My Documents\
esprit-rwd\patternlab\core\lib\CSSRuleSaver\SelectorDOM.php on line 95
```
Is there something I can do fix this?

Thanks!

**Comment by simonvart** [comment]
Same here. There is a CSS selector that breaks the function. If I erase the content from source/css/style.css file, the error flies away. I'm using bootstrap 3.3.4 as a stylesheet.

**Comment by bjornwang** [comment]
Getting the same error here now. Appeared suddenly after i renamed and moved some files to clean up my structure. Any new insight as to how I can "repair" Pattern Lab?

**Comment by simonvart** [comment]
Hi, this looks like a parsing error : check your files (maybe move them and
reintroduce them one by one to identify the guilty one). Could be a invalid
caracter or a syntax error in a mustache template.

2015-10-21 11:46 GMT+02:00 bjornwang <notifications@github.com>:

**Comment by bjornwang** [comment]
I was doing just that, reintroducing file after file. But the behavior is strange.

I found one file causing the error. If I empty it, no error. However, whatever i put in there, even if it's just a plain text like "TEST" or a simple tag, <div>TEST</div> it crashes. No funny characters. What's more, this is the standard Pattern Lab _00-head.mustache file, unchanged for weeks. something told me the error is elsewhere.

On top of this, I found I have 20+ other files causing the same problem, and these seem to be byte by byte identical to a folder backup from yesterday that runs without problems. For the life of me, I cannot understand what causes this.

I'm reverting to a copy of my backup, and moving the few changes I did today back into files in the backup.

**Comment by simonvart** [comment]
maybe authorisation problem ? Maybe try to output the node to check what's
inside.

2015-10-21 12:30 GMT+02:00 bjornwang <notifications@github.com>:

**Comment by bjornwang** [comment]
Reverting to my backup removed the problem, so now I cannot reproduce the error anymore. Would have like to have helped solve it.

**Comment by simonvart** [comment]
if it happens again, maybe copy the file structure and the backup next to
each other and have a diff to check differences.

2015-10-21 13:36 GMT+02:00 bjornwang <notifications@github.com>:

**Comment by bjornwang** [comment]
This seems to be the exact same problem that is described in this thread:
https://github.com/pattern-lab/patternlab-php/issues/105
