### ISSUE TITLE
Generating Pattern Lab For the First Time, Public Folder Not Generating, Errors Recieved 

### ISSUE THREAD

**Issue by wcavalari** [pattern-lab/patternlab-php#309]
After a fresh install of Pattern Lab, I followed these steps. (http://patternlab.io/docs/first-run.html)

    1. Open core/scripts/
    2. Double-click generateSite.command

This ends up throwing errors.
"No such file or directory in .../pattern-lab/core/lib/PatternLab/Builder.php on line 1264
Either the public directory for Pattern Lab doesn't exist or the builder is in the wrong location. Please fix."

I also tried php core/builder.php -g with the same result.

I am not able to generate a Public Folder. 

Any advice on a fix would be greatly appreciated.
 - Do I need to move the Builder.php file or is there a work around?

**Comment by bradfrost** [comment]
Hey @wcavalari,
I followed your same steps and it successfully generated: 

<img width="485" alt="frostbd generatesite command 80x24" src="https://cloud.githubusercontent.com/assets/383701/8887604/74ad1580-3257-11e5-95ac-3451a967a067.png">

I'm not exactly sure what could be causing the issue. @dmolsen, do you have any ideas?

**Comment by wcavalari** [comment]
Thank you for the reply Brad. I ended up downloading Pattern Lab again and replacing the files in my project folder with the new downloaded content.  Everything is running fine now.
