### ISSUE TITLE
Renaming atoms to elements

### ISSUE THREAD

**Issue by Themikeross** [pattern-lab/patternlab-php#310]
I've been working to try to change the nomenclature of "atoms" to "elements" per a business request (I know it's stupid, but sometimes I gotta do what I'm told :( ).

Once the directory './source/_patterns/00-atoms' is renamed to: './source/_patterns/00-elements', and every reference to "atom(s)" is changed to "elements", the site generates properly. However the source index.mustache doesn't generate the style tag to pull in the main style.css. 

None of the styles outlined in ./public/css/style.css seem to be added, the file is never loaded. Any help would be appreciated. 

Thank you.

**Comment by bradfrost** [comment]
@Themikeross, 
Hmmm, that doesn't sound like it would be related to the name change. Can you confirm that changing things back to atoms (or trying to change it on a fresh install) prevents the stylesheet from getting pulled in? Thanks

**Comment by Themikeross** [comment]
Yes, reverting back to 'atoms' from 'elements', and then building seems to clear up the issue. I have also tried to build fresh after renaming: './core/source/_patterns/00-elements' and then doing an initial build  php core/builder.php -g

Both build properly without error, but do not load the main style.css.

**Comment by retsoced** [comment]
@Themikeross I saw the same behavior, so I ended editing (aka hacking) the patternNav.mustache file to change the name and left the atoms folder in place.

**Comment by patrickbjohnson** [comment]
Wish there was an option to configure the patterns naming conventions as I've had simliar requests from business folks.
