### ISSUE TITLE
View Code not working in Chrome browsers

### ISSUE THREAD

**Issue by bjornwang** [pattern-lab/patternlab-php#313]
Selecting "Code" from the View menu does nothing in Chrome browsers on Mac.
The annotation view works as intended.

Looking at the code, the #sg-code-container DIV is not modified to be shown onscreen in Chrome, but just sits outside view. Also, If I modify the placement, so it becomes visible, the tabs still doesn't actually show the code.

Works well if I switch to Safari for example.

**Comment by retsoced** [comment]
@bjornwang What version of Chrome are you running? I'm using Version 44.0.2403.130 (64-bit) on Yosemite and have no issues with Chrome, Firefox or Safari.

**Comment by bjornwang** [comment]
Version 44.0.2403.130 (64-bit). Same as you. Haven't made the leap to Yosemite yet, though.

Might be a local thing, but I'm not experiencing trouble with other websites.

I should mention that this only applies when viewing one element. The code panes do become visible when viewing "all" alements.

Could this be some access issue caused by opening the generated Pattern Lab site from file, possibly? The old --allow-file-access-from-files flag didn't do the trick, though ...

**Comment by retsoced** [comment]
Yeah, it's totally because you're opening the site from a file. It throws a XMLHttpRequest request when it tries to load the page into codeviewer.js. I would just run it through the OS X built-in Apache and be done with it.

**Comment by bjornwang** [comment]
My bad then, sorry to be wasting your time. Wasn't aware of the different security models for Chrome and other browsers. Thanks for clearing that up.
