### ISSUE TITLE
Question: constraining size of SVG images atoms in patternlab

### ISSUE THREAD

**Issue by JeNeSuisPasDave** [pattern-lab/patternlab-php#322]
I added some SVG images as atoms. **Problem:** They display as _huge_ graphics in the list of image atoms -- because they will dynamically scale to the full width of the viewport!

I want to constrain their width when displayed as a standalone atom in the style guide (e.g. to something 5em wide), but not impose that width when they are part of molecules or modules.

I don't see a clean way to select and style _only_ the SVG images in only the atom pages in the style guide. **What is the best way to get what I'm looking for?**

**Comment by bradfrost** [comment]
Hey @JeNeSuisPasDave,
Thanks for your question. If you want to edit the styles of elements _only_ within Pattern Lab, you can edit the file: `/public/styleguide/css/styleguide-specific.scss`

**Comment by simonvart** [comment]
Just a thought : I had the same issue and solved it by adding CSS inline styles inside the mustache template (<style>... CSS...</style>)

**Comment by JeNeSuisPasDave** [comment]
@simonvart,

The problem with putting inline style in the mustache template is when you try to compose larger things (molecules, organism) with that SVG image atom then the inline style on the atom will trump any styling associated with the composed entity. Not good.

What I would prefer is that the the styleguide generator add a class that indicates what kind of 'thing' the style guide page is displaying (e.g., the div wrapping the 'thing' could have a class of 'sg-atom' or 'sg-molecule', or 'sg-organism'). If we had that, then I could add a style to `styleguide-specific.scss` that constrained the size of SVG atoms to 5em width, for example, without impacting their size inside other style elements (like molecules or organisms).

**Comment by bradfrost** [comment]
@JeNeSuisPasDave,
One way you could achieve this is targeting something like `.sg-pattern-body > svg`, which means that if an SVG is a direct descendent of `.sg-pattern-body`. So if the SVG is included in molecules or organisms elsewhere, it would most likely appear inside of other tags so the styles wouldn't be applied. Does that make sense?

Thanks for the suggestion about the `sg-atom`, `sg-molecule`, etc suggestion. @dmolsen and I will keep it in mind.
