### ISSUE TITLE
Css is not updated 

### ISSUE THREAD

**Issue by ChristophGerl** [pattern-lab/patternlab-php#325]
First of all, I have got pattern-lab installed on a branch of my local repository on my Mac. 
So I changed the $font and $font-secondary variable in the _variables.scss file. After this, if I run console sass on the style.scss file in the output the fonts are still the old ones. If I run the Script generateSiteWithCSS also nothing changes.
What can be the Problem?

**Comment by bradfrost** [comment]
Hey @ChristophGerl,
It's tough to see exactly what you're struggling with, but I'd recommend opening the pattern in a new window (view > open in new window) and refreshing a few times. Sometimes the page gets cached and new updates don't show right away. Once the cache is flushed then you should be able to refresh the page in the context of the Pattern Lab shell and see the changes. Hope that works!
