### ISSUE TITLE
Pattern Lab as website building framework?

### ISSUE THREAD

**Issue by ChristophGerl** [pattern-lab/patternlab-php#326]
Hello,

Is pattern lab meant to be a whole website building framework with the pattern system or is it only supposed to help with creating a design concept but the whole implementation should be done without pattern lab?

Thanks in advance,
C. Gerl

**Comment by bradfrost** [comment]
Hey @ChristophGerl,
Thanks for your question. This may help clear things up a bit: http://atomicdesign.bradfrost.com/chapter-3/#just-what-exactly-is-pattern-lab

Pattern Lab is a tool to help you build pattern libraries, but is not a tool that you will use to launch a website. I myself Pattern Lab to create production-level frontend code, and then translate that code into a content management system. Does that help?
