### ISSUE TITLE
PHP Warning:  file_put_contents(..): failed to open stream: No such file or directory in Z:\PatternLab\Builder.php on line 346

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#327]
Hi,

When generating I keep getting lots of warnings like this:

PHP Warning:  file_put_contents(Z:\AlexL\My Documents\esprit-rwd\patternlab\core
\lib\PatternLab/../../../public/patterns\00-atoms-01-global/index.html): failed
to open stream: No such file or directory in Z:\AlexL\My Documents\esprit-rwd\pa
tternlab\core\lib\PatternLab\Builder.php on line 346

I removed each folder one by one and generated each time from /source/_patterns to test if it was something in there, but I still get them. Any idea what could be wrong? It's so difficult to debug.

Thanks for your help!

**Comment by Machinas** [comment]
Any idea please, it doesn't even generate the html files in public now

**Comment by simonvart** [comment]
Hi, hard to tell from your info, have you checked the path, the file and the rights upon the file ?

**Comment by dmolsen** [comment]
@Machinas -

And you definitely have a `public/` directory?  I'm assuming it's a permissions issue as I don't recall problems on Windows for PL1 but maybe I'm forgetting a path issue at some point.
