### ISSUE TITLE
Prevent upgrade of 003-move-styleguide

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#328]
Hi,

When generating patternlab I get:

upgrading your version of pattern lab...
checking for migrations...
   Starting the 003-move-styleguide migration...
   Completed the 003-move-styleguide migration...

I want to avoid this because it resets the styleguide.scss, and I have edited that in my version. How can I prevent this from happening?

Thanks!

**Comment by dmolsen** [comment]
@Machinas -

Seems like there's something wrong with storing the version info in `config/`. Regardless, you can remove `core/migrations/003-move-styleguide.json` to stop the migration from happening.
