### ISSUE TITLE
Curious about .gitignore on source (question, not an issue)

### ISSUE THREAD

**Issue by hdwebpros** [pattern-lab/patternlab-php#329]
I'm just curious, as I want to learn to do the best practices. If I clone and work on a Patternlab, push my changes to a repo, go home and pull the repo, it doesn't have any of the source files I worked on.

Is that by design? Should I be doing this in a different way?

**Comment by dmolsen** [comment]
It was to make sure we didn't do anything in development that leaked over into the repo. Feel free to remove that line from the `.gitignore`.
