### ISSUE TITLE
Pattern states with pseudo patterns fail to buile

### ISSUE THREAD

**Issue by lostsatellites** [pattern-lab/patternlab-php#330]
I have a pattern with the @inprogress state and a few pseudo patterns off it it which also have their own states, but when the build happens there are patterns that can't be generated because the psuedo patterns are looking for the mustache file without the state. I tried including the state within the json file name, so pattern@inprogress~pseudopattern.json and that didn't work. Any thoughts? Guessing I'm mixing up something in there.

**Comment by dmolsen** [comment]
@lostsatellites -

Could you give me the file names you're trying to use? Just want to be able to make sure my test matches your use case. Thanks.

**Comment by lostsatellites** [comment]
I'm using…

00-header@inprogress.mustache
00-header~alpha@complete.json (also tried this without the status)
00-header~authenticated@inprogress.json
…

**Comment by dmolsen** [comment]
@lostsatellites -

Bad code on my part. Just did a quick test and the following should work but please test yourself. Replace [line 739 in Builder.php](https://github.com/pattern-lab/patternlab-php/blob/e52ced8551000b7c6b97a01f419e2af8a07e2fd1/core/lib/PatternLab/Builder.php#L739) with the following:

```php
"patternSrcPath" => $this->patternPaths[$patternTypeDash][$patternBaseDash]["patternSrcPath"],
```

That should give the correct path to the parent pattern.

**Comment by lostsatellites** [comment]
I replaced that and am still getting the same error.

**Comment by dmolsen** [comment]
@lostsatellites -

I duplicated your use case exactly and my fix worked on a clean install of PL so I'm unsure why it'd still be a problem. Can you please paste [lines 738-742 from Builder.php](https://github.com/pattern-lab/patternlab-php/blob/e52ced8551000b7c6b97a01f419e2af8a07e2fd1/core/lib/PatternLab/Builder.php#L738-L742) here please? Thanks.

**Comment by lostsatellites** [comment]
```$patternInfo = array("patternPath"    => $patternPathDash."/".$patternPathDash.".html",
										 "patternSrcPath" => $this->patternPaths[$patternTypeDash][$patternBaseDash]["patternSrcPath"],
										 "patternName"    => ucwords($patternClean),
										 "patternState"   => $patternState,
										 "patternPartial" => $patternPartial);```

**Comment by dmolsen** [comment]
@lostsatellites -

I just downloaded a clean install and redid the test and, again, it works. I assume I'm missing something unique about your use case. If you can share further details I'll look into it more but for now I'm stuck. Sorry.

**Comment by lostsatellites** [comment]
I appreciate you looking into it. I'll try a clean install and see if anything changes.
