### ISSUE TITLE
Trouble Getting started with SCSS

### ISSUE THREAD

**Issue by nickfedoroff** [pattern-lab/patternlab-php#331]
When I edit the scss files in `source/css/scss/objects/<file>.scss` and run `generateSiteWithCSS.command`, the css isn't updated. I'm sure I'm missing something. Why isn't the scss recompiling automatically?

**Comment by dmolsen** [comment]
@nickfedoroff -

Pattern Lab doesn't support compiling Sass. Those files are just an artifact of putting the project together originally. We specifically made the choice to not support a particular flavor of precompiled CSS. This is from the docs regarding the "Generate Site with CSS" feature:

```
When using this feature, Pattern Lab can display only those CSS rules that affect a given pattern on the pattern detail view. This might be useful if you have a large Sass-generated CSS file or framework but only need a sub-set of styles that may affect a small piece of mark-up or pattern.
```

If you'd like to use Sass you'll want to use your favorite task runner.
