### ISSUE TITLE
Cache is being a persistent issue in Chrome

### ISSUE THREAD

**Issue by hdwebpros** [pattern-lab/patternlab-php#332]
Any tips on how to not make generated HTML cache in Chrome? Like a setting I can change or something?

**Comment by dmolsen** [comment]
Got a version of Chrome I can try this against? How are you refreshing the HTML (e.g. manually, letting the native web socket server try to handle it, browser sync)? Which views are affected (e.g. view all and/or individual patterns)?

We've tried to be smart about adding cache buster query string variables to URLs by default. Doesn't mean a browser will continue to support that hack though.

**Comment by hdwebpros** [comment]
I'm using Version 47.0.2526.106 m
I'm refreshing manually. (f5 or refresh icon)
It's effected sporadically. Of course, now it seems to be working fine. It almost seems like the initial build or two gets cached, and everything after doesn't. I'm using the 'watcher' -w to build.
