### ISSUE TITLE
Patternlab is not responding to width of browser

### ISSUE THREAD

**Issue by yratof** [pattern-lab/patternlab-php#333]
Just noticed that the site seems to not be responsive right now, this is latest chrome in latest osx, with the browser being small at less than 530px

<img width="528" alt="screen shot 2016-01-11 at 08 57 57" src="https://cloud.githubusercontent.com/assets/1001935/12228883/852d99be-b841-11e5-931b-f270dd7f3001.png">

**Comment by dmolsen** [comment]
@yratof -

I'm not sure that's really supposed to work honestly. Looks like other patterns are working properly (e.g. the header organism).
