### ISSUE TITLE
How do you change the breakpoint values for S, M, L in the nav?

### ISSUE THREAD

**Issue by Machinas** [pattern-lab/patternlab-php#334]
In which file can I amend this Thanks!

**Comment by dmolsen** [comment]
That's going to be in `public/styleguide/js/styleguide.js`. You'll want to look at lines 90-128. [Example](https://github.com/pattern-lab/patternlab-php/blob/e52ced8551000b7c6b97a01f419e2af8a07e2fd1/core/styleguide/js/styleguide.js#L90-L128)
