### ISSUE TITLE
can't see code

### ISSUE THREAD

**Issue by vlrprbttst** [pattern-lab/patternlab-php#336]
i'm running patterlab-php on a mac, i have the watch and reload activated with `startWatcherWithAutoReload.command` but when i click on the code link in the patternlab menu, i can't see any code:

![](http://i.imgur.com/lEdxLfo.png)

i just dragged the `index.html` file from the finder to chrome.

**Comment by bradfrost** [comment]
Hey @vlrprbttst, 
Are you able to see if you're getting any errors in dev tools? And can you test it against the demo version [here](http://demo.patternlab.io/?p=atoms-headings)? And lastly, perhaps it's a browser issue? Perhaps trying in another browser to see if that works?

**Comment by vlrprbttst** [comment]
hey brad, sorry for not being specific enough with my issue. this weekend i had the opportunity to test it also on a windows machine, I'm on Chrome but i get the same exact behaviour.

here's what i do:
- i double click on `core/scripts/startWatcherWithAutoReload.command`
- i double click on `public/index.html`

i do get an error on the console as i open it:
![](http://i.imgur.com/3IevinH.png)

and if i click the *code* link on the patternlab menu bar, i get some more:
![](http://i.imgur.com/pUOArNq.png)

do I need an apache server running for this to work or is it something else?

thanks for this great work btw, i've been spending my last week studying it and trying to integrate it.

**Comment by vlrprbttst** [comment]
using browser sync's built-in static server, the problem disappears
