### ISSUE TITLE
pattern-specific JavaScript files

### ISSUE THREAD

**Issue by Frikki** [pattern-lab/patternlab-php#338]
Where should I keep pattern-specific JavaScript files? For example, a *buttons.js*?

**Comment by bradfrost** [comment]
Hey @Frikki,
That's up to you, really. The way I set things up by default has JavaScript files living in a `/source//js` folder. You can change this to `/source//javascript` or whatever you want. However, I'm not sure how bundling JavaScript files with the template files in `/source/_patterns` would work. @dmolsen, do you happen to know?
