### ISSUE TITLE
Multiple molecules  inclusion and paramteric namespace

### ISSUE THREAD

**Issue by zioigor** [pattern-lab/patternlab-php#340]
I have a page that references a template which includes similar molecules many times, because I have different json data I wanna fit in:

```
{{> molecules-list-unordered-with-title-itemsA:(par1:"Value")}}
{{> molecules-list-unordered-with-title-itemsB:(par1:"Value")}}
{{> molecules-list-unordered-with-title-itemsC:(par1:"Value")}}
```

With molecule structured as:

```
<div class="{{styleModifier}}">
	<h4>{{par1}}</h4>
	<ul>
		{{# arrayJsonA }}
			<li> {{> atoms-link-simple}} </li>
		{{/ arrayJsonA }}
	</ul>
</div>
```

Other molecules just differ in the namespace iterator (arrayJsonB, arrayJsonC), which corresponds to a json array of data I use for the inner atom (atoms-link-simple), like this:

```
<div class="{{styleModifier}}">
	<h4>{{par1}}</h4>
	<ul>
		{{# arrayJsonB }}
			<li> {{> atoms-link-simple}} </li>
		{{/ arrayJsonB }}
	</ul>
</div>
```

and so on for "arrayJsonC" , etc... etc...
Each namespace refers to a different json data array.

I know it sounds a little bit OT, but It would be nice If I could define a "parametricnamespace" so that I could use a single molecule able to access different data structures when included inside a page:
```

{{> molecules-list-unordered-with-title:(par1:"Value", parametricnamespace: "arrayJsonA" )}}
{{> molecules-list-unordered-with-title:(par1:"Value", parametricnamespace: "arrayJsonB" )}}
{{> molecules-list-unordered-with-title:(par1:"Value", parametricnamespace: "arrayJsonC" )}}
```

I guess I have a tagging problem. 
The following syntax obviously doesn't work, but just to give you an idea :):)

```
<div class="{{styleModifier}}">
	<h4>{{par1}}</h4>
	<ul>
		{{#  {{parametricnamespace}} }}
			<li> {{> atoms-link-simple}} </li>
		{{/ {{parametricnamespace}} }}
	</ul>
</div>
```

Is there already a way I am ignoring to achieve this with Patternlab (PHP version) current syntax?
Are there any planned devs pointing in this direction?

TIA,
Igor

**Comment by bradfrost** [comment]
Hey @zioigor,
Thanks for your question. I'm not sure if this will exactly answer your question, but here it goes. In order to accomplish what I think you need, you can structure things this way:

Your molecule code can look like:
````
<div class="{{styleModifier}}">
    <h4>{{part}}</h4>
    <ul>
        {{# array }}
            <li> {{> atoms-link-simple}} </li>
        {{/ array }}
    </ul>
</div>
`````
This sets it up to be an agnostic element. Then, when you include that molecule in your template you can include it like so:

``````
{{#itemsA}}
{{> molecules-list-unordered-with-title }}
{{/itemsA}}

{{#itemsB}}
{{> molecules-list-unordered-with-title }}
{{/itemsB}}

{{#itemsC}}
{{> molecules-list-unordered-with-title }}
{{/itemsC}}
`````
Now, your page's JSON file could look like:
``````
{
   "itemsA" : {
      "styleModifier" : "class-name-1",
      "Part" : "h4 title 1",
      "array" : [
        { "link" : "link stuff" }
      ]
  }
},
{
   "itemsB" : {
      "styleModifier" : "class-name-2",
      "Part" : "h4 title 2",
      "array" : [
        { "link" : "more link stuff" }
      ]
  }
},
{
   "itemsC" : {
      "styleModifier" : "class-name-3",
      "Part" : "h4 title 3",
      "array" : [
        { "link" : "even more link stuff" }
      ]
  }
}
``````

Does this help solve your problem? One of the issues with leaning on pattern parameters too hard is that it doesn't provide a true separation between structure and data. That's why the JSON approach is preferred (in my mind at least).

**Comment by madpixl** [comment]
Thank you. A do think it is a fantastic product. I love how flexible it is already. Your example will help me find a solution, I'm sure.
