### ISSUE TITLE
Will not update after initial build

### ISSUE THREAD

**Issue by eyeamaman** [pattern-lab/patternlab-php#343]
Not sure if it is me but...

1. Download the latest version and unzip.
2. cmd line to the folder and run $ php core/builder.php -g
3. View site - GREAT
4. Change any template, say source/_patterns/00-atoms/02-text/00-headings.mustache
5. Run $ php core/builder.php -g
6. See that no change has happened on page refresh.

- Even looking into the public folder at the headings files.
- Even if you delete the patterns folder in public and run the build again
- Even after running the build with nocache.
- Even though this is odd

ALSO

Upon deleting the entire contents of the folder bar the README file.  It completely errors:

    ERROR: the main style guide wasn't written out. make sure public/styleguide exists. can copy core/styleguide
    your site has been generated...

All running with:

1. Windows 10
2. PHP 5.6.18

**Comment by eyeamaman** [comment]
OMG so I was editing in /core/source and not /source.

Kind of interesting that /source/* is added to git ignore.  Should it be the case that we edit code/source and remove the contents of /source and /public.

if you're making lots of updates along with other people I'd want /source to be uploaded as well based on the way this build seems to work.

Or do you edit in both /core/source/ && /source?

**Comment by bradfrost** [comment]
@eyeamaman, all updates should be made in `/source/` not `/core/source/`. I'm not sure why `/source/*` is added to `.gitignore`; @dmolsen is it because of how Pattern Lab is initially built?
