### ISSUE TITLE
«Using Pseudo-Patterns» documentation improvement

### ISSUE THREAD

**Issue by bjornte** [pattern-lab/patternlab-php#346]
In my opinion, this page could benefit from some rearrangement:
http://patternlab.io/docs/pattern-pseudo-patterns.html

I would start with the example. As it currently is, for a non-programmer such as myself, the initial paragraphs are easier to understand after having seen the «00-homepage~emergency.json» part.

**Comment by bradfrost** [comment]
@bjornte Thanks for the suggestion. We'll be revisiting the documentation for the new version of Pattern Lab and will definitely keep this in mind.
