### ISSUE TITLE
$ php builder.php -wr websocket issues on linux

### ISSUE THREAD

**Issue by dibs** [pattern-lab/patternlab-php#349]
If I run **pageFollow.php** or **autoReload.php** individually they work fine and my PL reports no issues.
I can run them in tandem and all is well.

If I try to run `$ php builder.php -wr` websocket errors appear in regard to the **pageFollow.php** connection.

I have tried to alter ports in **config.ini** to see if it was some kind of conflict but still have not managed to get **builder.php** to start both scripts without issues. 

Error: WebSocket connection to 'ws://patternlab.mch:54304/pagefollow' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED

**Comment by pigstake** [comment]
I have what I think is a similar issue on Mac:

```WebSocket connection to 'ws://127.0.0.1:8003/pagefollow' failed: Error in connection establishment: net::ERR_CONNECTION_REFUSED```

Mac 10.11
Chrome 48.0.2564.116

I am untechnical enough to not know how to debug :cry:

**Comment by pigstake** [comment]
@dibs Any luck with this in the past day?

**Comment by dibs** [comment]
@pigstake Nope

**Comment by yumyo** [comment]
+1

**Comment by joemewes** [comment]
+1
