### ISSUE TITLE
Should I use patternlab-php or patternlab-php-core?

### ISSUE THREAD

**Issue by mpdude** [pattern-lab/patternlab-php#352]
I'd like to hack a bit on PL and PHP and see whether I can integrate it with an existing project using Twig. The goal is to be able to install PL as an add-on dependency to that project, use it as a styleguide generator and be able to directly share existing Twig templates and macros between both PL and the project's "production" templates.

Initially `patternengine-php-twig` and its dependency `patternlab-php-core` seemed a good start. But then I found that `patternlab-php` itself does not (Composer-)depend on `patternlab-php-core`. 

So, was `patternlab-php-core` an attempt to take core functionality out of `patternlab-php`? Was that successful or have you abandoned that idea?

Given that `patternlab-php` was the "original" project and has a lot more GitHub stars and forks, would it be better to use that as a starting point?

Or, should I even forget about the PHP version and try Node.js instead? The Node port seems to have a lot more activity than the PHP one.

Probably @dmolsen can tell best about the relation of `...-php` and `...-php-core`?

**Comment by dmolsen** [comment]
Try this repo if you want to play with Twig. 

https://github.com/pattern-lab/edition-php-twig-standard

Core has largely been successful in replicating the bulk of the core logic of PL1. It's just one part of a pattern lab edition though. PL2 is way more modular than PL1.

**Comment by mpdude** [comment]
So, `patternlab-php` is PL1 and `patternlab-php-core` is the core of PL2?

To me it seems most of the folks using the PHP version (and not Node.js) stick with `patternlab-php`, so this probably has the best community support and most of the PRs?

**Comment by dmolsen** [comment]
PL2 isn't 100% finished. When it is we'll be updating the code here to take advantage of it. This will continue to be the repo with the most stable version of the PHP edition. Again, PL2 is comprised of a bunch of modules as opposed to one monolithic repository. It'll be more in line with symfony and laravel.

**Comment by dmolsen** [comment]
PL2 is now live in this repo.
