### ISSUE TITLE
Renumbering meta templates (header and footer) breaks PL

### ISSUE THREAD

**Issue by MikeAHenry** [pattern-lab/patternlab-php#353]
When I changed the names of the _00-header and _01-footer files to remove the numbering, they did not get inserted into the generated html files, and the Pattern Lab viewer stopped working.

It looks like maybe these lines are the culprit:
```
  $patternHeadPath    = __DIR__.$this->sp."00-atoms/00-meta/_00-head.mustache";
  $patternFootPath    = __DIR__.$this->sp."00-atoms/00-meta/_01-foot.mustache";
```
(core/lib/PatternLab/Builder.php:975-976)

Is there a reason these are hard-coded values? (i.e., should we refrain from renaming or renumbering the files and atom directory?)

**Comment by dmolsen** [comment]
@MikeAHenry -

This has been addressed in PL2. It won't be fixed in PL1. And the reason is that it was a dumb design decision on my part.
