### ISSUE TITLE
Including .mustache file with JSON data in higher level pattern.

### ISSUE THREAD

**Issue by madpixl** [pattern-lab/patternlab-php#355]
I would like to have a generic  THEAD that gets its THs from JSON included in a Table Organism that is included in a Page. Same with a couple TBODY rows. 

```
<thead>
      <tr> 
             {{#tableheadercells}}
            <th {{htmlAttr}} class="{{cssClass}}">{{{content}}}</th>
              {{/tableheadercells}}
          </tr>
</thead>'
```

Works fine on its own...

But I would like to use this above mustache partial in a page containing the entire table. Is this possible?
I've googled for an answer, but haven't found a good one. Seems like you could sequence html rendering order by pattern type and there would be no JS confusion and PHP could even be easier since you can have more control over processing order in relation to pattern hierarchy... or am I just too new to this whole thing?

**Comment by madpixl** [comment]
Crickets

**Comment by dmolsen** [comment]
@madpixl -

You don't get an answer in 17 hours and decide you need to follow-up with "Crickets?" Nice... A page cannot see the JSON for included organisms and molecules.

**Comment by madpixl** [comment]
Sorry if crickets comment was inappropriate. I don't go on the public Github as often and our internal network is more active... 

I'm trying to promote use of Patternlab as our reference html/css pattern library and feeling a lot of pressure to make it work for us. If it works I'm the hero, if not I've wasted a lot of time. 

I already found out that the JSON data was not seen, but I was wondering if there was a way around that. Maybe forcing a render prior to inclusion for higher level objects, so the basic deconstruction of patterns could be more consistent. 

I guess I will have to dig a little deeper to figure out if I can make it happen on my own. My premise was to share the JSON file developers use with DRULEs to render the Angular UI for our HTML-only reference application so that the partials could be leveraged more easily, and we could share more code on a variety of levels.

**Comment by bradfrost** [comment]
@madpixl [Here's an example](https://github.com/pattern-lab/patternlab-php/issues/340#issuecomment-181032466) that might be of use to you. You can set up initial data in `data.json` and override that data at the page level. You can wrap individual instances of a pattern in a name, then target the data in the JSON.

Please keep in mind that this is an open-source project that is driven by people who have full-time jobs, families, and other responsibilities.

**Comment by dmolsen** [comment]
@madpixl -

A pre-render would defeat the purpose of Pattern Lab. A pattern could have one and only one block of data used to render it. No overrides possible.

The thing you could do is muck with how PL builds the global data store from data.json. Rather than just read in that one file you could scan all of the patterns for their individual JSON files and tack their data onto that global store of data. You'd have to be careful with namespacing but it's doable.

Really not sure we'll be much more help. Sorry.

**Comment by madpixl** [comment]
Thx.
