### ISSUE TITLE
pattern-finder.js - try/catch for receiveIframeMessage()

### ISSUE THREAD

**Issue by christianhaller** [pattern-lab/patternlab-php#357]
If there are some other messages triggering
`````
window.addEventListener("message")
````
the JSON.parse(event.data) fails.
````
JSON Parse error: Unexpected identifier...
````
It's in 8 files /core/styleguide/js

**Comment by dmolsen** [comment]
@christianhaller -

Thanks for the heads up on this. It's been implemented as part of the Pattern Lab 2 release. It won't be fixed in PL1. I apologize for the delay.
