### ISSUE TITLE
styleguide.html

### ISSUE THREAD

**Issue by jacobthemyth** [pattern-lab/patternlab-php#361]
My team is having a hard time figuring out how to create our pattern library
based on Pattern Lab in a way that we can store it in git and have a team member
clone the repository and issue a simple command without having to be familiar
with the terminal, or even possibly front end development.

My understanding of Pattern Lab is that `styleguide.html` (i.e.
`public/styleguide/html/styleguide.html`) is an HTML file that is generated by
PatternLab and is the landing page of the pattern library (it's the page you see
in the iframe when you go to the root URL or click "View All"), so it changes
any time any of the patterns change. However, in order for PatternLab to
generate the contents of `styleguide.html`, the file needs to already exist (but
doesn't have to have any particular contents).[^1]

So, since `styleguide.html` is essentially a build artifact, we don't want to
check it into git (to avoid noisy diffs and merge conflicts). But since it must
exist on disk for the build to work, we have to copy it manually in order for
the build to work.

The only options we've come up with are to a) add `public/styleguide` to
`.gitignore` (really, we have `public/*`) and copy `core/styleguide` into
`public` by hand every time we clone the repository b) track `public`, and deal
with noisy diffs and merge conflicts or c) Change the code in `core`[^2]. Is
there any way I can improve my mental model of the system, or is this an
inherent quality of PatternLab? How are other projects solving this problem?

Thanks!

[^1]: https://github.com/pattern-lab/patternlab-php/blob/master/core/lib/PatternLab/Builder.php#L218-L222
[^2]: https://github.com/pattern-lab/patternlab-php/issues/223

**Comment by dmolsen** [comment]
@jacobthemyth -

This is just an inherent issue with PL/PHP1. In the short-term changing the code in `core` is the only way to sidestep it. As noted in the other issue it was a bad assumption on my part. Sorry.

**Comment by jacobthemyth** [comment]
Cool, thanks! Just wanted to make sure I wasn't missing anything :)
