### ISSUE TITLE
Pass HTML with Pattern Parameters

### ISSUE THREAD

**Issue by amazingrando** [pattern-lab/patternlab-php#362]
**Issue:** I would like the option to use Pattern Parameters to pass HTML into a template. Currently all HTML is converted to text.

<img width="569" alt="screenshot 2016-06-23 12 00 16" src="https://cloud.githubusercontent.com/assets/409903/16310327/261413a2-393a-11e6-8263-0b7fbc11e0bf.png">

**Steps to recreate:** This was discovered while using [Exercise 2 of the starterkit](https://github.com/pattern-lab/starterkit-mustache-webdesignday) from Web Design Day.

**Comment by acheloos-m** [comment]
You need to use trippel curly brackets in your mustache template. Otherwise all html content is escaped by default. Have a look here: 
http://patternlab.io/docs/data-json-mustache.html
and here 
https://mustache.github.io/mustache.5.html#TAG-TYPES

**Comment by amazingrando** [comment]
@acheloos-m Could you provide a working code sample of passing HTML through a Pattern Parameter? I was not successful.
- Using triple brackets on the outside makes the button not render, e.g.`{{{> atoms-btn(buttonText: "<p>&nbsp;&nbsp;💩&nbsp;&nbsp;</p>") }}}`
- I also tried using a variable inside the `buttonText` but that just renders the variable name and not the content, e.g. `  {{> atoms-btn(buttonText: {{hero.intro}}) }}
`

**Comment by acheloos-m** [comment]
The tripple mustaches go into your button template, not in the partial..
In your case use the partial in your molecule as you did in first place: 
`{{> atoms-btn(buttonText: "<p>&nbsp;&nbsp;💩&nbsp;&nbsp;</p>") }}`

Then, inside your btn template (00-atoms folder) use:
`<button> {{{ buttonText }}} </button>`
The HTML is escaped while the engine puts the pieces together, not when declaring vars. I've just tried it and it works.

**Comment by dmolsen** [comment]
@amazingrando -

@acheloos-m is right. Looking at my code if the variable to be replaced is set to `{{{ varname }}}` in the template then the pattern parameter is outputted as raw. If the variable to be replaced is set to `{{ varname }}` in the template then the pattern parameter is outputted as escaped.

I'm sort of forgetting what's in the depth of my code. Found some fun things that could be done with pattern parameters by looking at it ;)

Let me know if that does the trick and if I can close the issue.

**Comment by amazingrando** [comment]
@dmolsen @acheloos-m Confirmed as working. I'm closing this issue. Thank you both for attending to it.
