### ISSUE TITLE
Header and Footer are not re-generated

### ISSUE THREAD

**Issue by sbuckpesch** [pattern-lab/patternlab-php#367]
Hi there,

I setup a fresh install of patternlab using
`composer create-project pattern-lab/edition-mustache-standard`

After that I modified the `source/_data/data.json` file and changed the `title` attribute to "Pattern Lab 123" and I added an example `<meta about="TEST">` Tag to the head.

Then I called `composer generate` to re-generate the public folder. Unfortunately the head-section is not updated and neither the updated title nor my example meta-tag appear in the `index.html` file of the public folder. I checked as well the options in `config/config.yml`, but as it is by default cleanPublic is set to 'true'

What could be the problem here? Any further information you need here?

Thanks a lot and respect for your great product :-) Exactly what I was looking for...

All the best,
Sebastian

**Comment by sbuckpesch** [comment]
Ok, just figured it out... The generated styleguide is embedded as iframe. The styleguides Url is `/styleguide/html/styleguide.html`. So I just edit the outer frame's index.html file manually. :-)

So you can close the issue... :-)

**Comment by dmolsen** [comment]
@sbuckpesch -

You're going to have to be a little careful with future updates to `pattern-lab/styleguidekit-assets-default`. That's where the `index.html` file comes from. I haven't tested but your change _might_ get overwritten during an update. I've been thinking about theming options and the config. I'll add a "title" option to the list of possibilities. Thanks much for the idea.

**Comment by sbuckpesch** [comment]
@dmolsen That would be really useful. As well the generated page title from your JS file `document.getElementById("title").innerHTML = "Pattern Lab - "+patternName;`
should be configurable. The patternName is not really nice in as page title. The pattern title from the patterns markdown or the patterns caption in the navigation would be better.

Thanks a lot,
Sebastian

**Comment by dmolsen** [comment]
Good catch. Thanks :)
