### ISSUE TITLE
Documentation for Upgrading from 1 -> 2

### ISSUE THREAD

**Issue by gjhead** [pattern-lab/patternlab-php#383]
Somrthing missing from the documentation in regards to upgrading from pl1 -> pl2 

Your universal JSON files may not work, if that's the case, do this:

in:  source/data/
If your files are named: "_data.jason" and "_listitems.json" , remove the underscore so that they are named "data.jason" and "listitems.json"

Also:

**Comment by frostyweather** [comment]
Close #383. This has been added to the "Upgrading" documentation. Thanks @gjhead.
