### ISSUE TITLE
Adding multiple classes via styleModifier not working

### ISSUE THREAD

**Issue by mawrhis** [pattern-lab/patternlab-php#392]
I've been trying to pass multiple classes to my pattern using default patternlab syntax:

`{{> patternType-pattern:class1|class2 }}`

and for pattern:
` <div class="{{styleModifier}}"></div>`

But only the class1 is being passed through. It does seem to work, when the pipe is left out and replaced with space like this:

 `{{> patternType-pattern:class1 class2 }}
`
but it only works for styleModifiers. It's impossible to pass other pattern parameters, like:
` {{> patternType-pattern:class1(message: "btn2") class2 }}`

I've tried to disable data inheritance plugin, but it didn't affect the behavior. There's no other thing that I'm aware of that might affect it, so it seems like a bug. 

any ideas where the problem could be?

**Comment by bradfrost** [comment]
@mawrhis Thanks for your question. 

I tend to workaround this issue like so:

```
{{> atoms-button(styleModifier: "btn--secondary btn--small") }}
```
