### ISSUE TITLE
Multi-source Support and Custom Starter Kits

### ISSUE THREAD

**Issue by dmolsen** [pattern-lab/patternlab-php#55]
This issues builds off of #45.

If we move the core PL view files out of `source/` that might give us the flexibility to add multi-site support to one install of PL. This way a group could handle multiple clients with just one version of PL rather than having to have multiple copies of PL to update when a new feature comes out. The directory structure might look like this:

```
- builder
- config
- core (where the core view files are)
- listeners
- public
    -- wvnano
    -- english
    -- admissions
- source
    -- wvnano
    -- english
    -- admissions
```

We could have a flag in `config.ini` that enables it and then allows the user to set which folder to build from. For example, maybe they're working on `english` and want to build out of `source/english/` into `public/english/`. Then on viewing it'd be `patternlab.localhost/english/`. 

On top of this we might be able to allow for a custom starter kit if someone has a common base of images, css, and patterns to start a project. Rather than blowing out `core/` and worrying about us overwriting it maybe we could add an additional `custom/` folder. Again, the feature is enabled in `config.ini`. Then when they add a folder to `source/` and try to generate for the first time it can copy the starter kit from `custom/`, build the site, and they're ready to go.

Thoughts?

**Comment by umesh-velir** [comment]
@dmolsen - wondering if there is a documentation to configure PL, the twig version for multi-site support?
