### ISSUE TITLE
Pattern-specific listItems

### ISSUE THREAD

**Issue by tylersticka** [pattern-lab/patternlab-php#74]
Two features I love in Pattern Lab:
- The ability to extend `_data.json` with pattern-specific data.
- The `listItems` helper.

It would be _so darn cool_ if you could extend `_listitems.json` similarly.

Example: I want a specific pattern to have a list of items with a human time difference. Ideally, it'd be neat if I could somehow specify a pattern specific `_listitems.json` file like this:

``` json
{
  "1": {
    "timeago": {
      "amount": "4",
      "unit": {
        "long": "years",
        "medium": "yrs",
        "short": "y"
      }
    }
  },
  "2": {
    "timeago": {
      "amount": "7",
      "unit": {
        "long": "minutes",
        "medium": "min",
        "short": "m"
      }
    }
  }
}
```

(There's also a chance I'm just treating `_listitems.json` as sacred when it really isn't.)

**Comment by karthi-siva** [comment]
how do we name listItems more then 20 ie: for 20: {{# listItems.twenty }}
