### ISSUE TITLE
Scripts don't work if run from a location that has spaces in the path

### ISSUE THREAD

**Issue by mattsims** [pattern-lab/patternlab-php#8]
For example, running the generateSite.command when it is stored at the following location:

`~/Documents/Folder With Spaces In The Name/patternlab/scripts/generateSite.command`

will fail with the error:

`Could not open input file: /Users/mattsims/Documents/Folder`

Easily fixed by editing the scripts and wrapping the $DIR variable in the php command in quotes, eg:

``` #!/bin/sh
DIR="$( cd "$( dirname "$0" )" && pwd )"
php "$DIR/../builder/builder.php" -g
```

**Comment by kristywelli** [comment]
Hi there - I'm having this error too, with Patternlab's Standard Edition for Mustache. Which core script shall I edit to enable spaces in the base directory?
